# Generated by Django 6.1.1 on 2026-09-19 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='boi',
            new_name='bio',
        ),
    ]
