# Generated by Django 6.1.1 on 2026-09-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_guild_description_alter_player_guild_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
